### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by Madusudanan** [scalanlp/chalk#29]
Just a question. From the wiki I can understand that this project spawned from Apache open NLP. The last commit I was seeing in this project was in 2014, but Apache open NLP seems pretty active.

I am just curious if development has halted or has it moved to another project.

We are a full scala shop so looking out for a reliable NLP library in scala.

**Comment by jasonbaldridge** [comment]
The project is currently halted, with no current plan or resources for further development.

OpenNLP has recently become much more active, so I'm hoping that the momentum building there leads to a much updated and more modern set of capabilities.

Also, in the interim, Matthew Honnibal created SpaCy for Python, and he made a number of great design decisions and an awesome implementation. I'd love to have something like that for the JVM ecosystem.

https://spacy.io/

**Comment by Madusudanan** [comment]
Apache Open NLP seems to be a decent library for the JVM. For basic NLP tasks even apache spark's ML pipeline has some decent utilities.

Can you please update that development has halted in the project's README, it will be helpful for people.

**Comment by jasonbaldridge** [comment]
Done: https://github.com/scalanlp/chalk/commit/fe169e44fd271cb2785b19d53e538b856ecfcaac
